name: tic
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  http: ^0.13.5
  google_maps_flutter: ^2.2.6
  flutter_screenutil: ^5.7.0
  eva_icons_flutter: ^3.1.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  carousel_slider: ^4.2.1
  intl: ^0.18.0
  url_launcher: ^6.1.6
  buttons_tabbar: ^1.3.6
  flutter_staggered_grid_view: ^0.6.2
  transparent_image: ^2.0.1




  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"


flutter: 
  uses-material-design: true

  assets:
    - assets/

