import 'package:get/get.dart';

class TranslateApp extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'setting': 'Change language',
          'akomodasi': 'ACCOMMODATION',
          'rs': 'HOSPITAL',
          'tukar': 'MONEY CHANGER',
          'rental': 'RENTALS',
          'agen': 'TOURS AGENT',
          'resto': 'RESTAURANT',
          'pasar': 'MARKET',
          'transport': 'TRANSPORTATION',
          'populer': 'Most Popular Tours',
          'gallery': 'GALLERY',
          'detail': 'DETAILS',
          'lokasi': 'LOCATION',
          'info': 'INFORMATION',
          'tour': 'TOUR',
          'event': 'EVENT',
          'berita': 'NEWS',
          'tipe': 'TYPE',
          'views': 'VIEWS',
          'pemilik': 'OWNER',
          'harga': 'PRICE',
          'sewa': 'RENTAL PRICE',
          'telp': 'PHONE NUMBER',
          'cp': 'CONTACT PERSON',
          'kab': 'REGENCY',
          'kec': 'SUBDISTRICT',
          'tarif': 'RATE TOUR',
          'indo': 'INDONESIA',
          'malay': 'MALAYSIA',
          'inggris': 'ENGLISH',
          'jepang': 'JAPAN',
          'china': 'CHINA',
          'india': 'INDIA',
          'rusia': 'RUSSIA',
          'korea': 'KOREA',
          'turki': 'Türkiye',
          'spanyol': 'SPANISH',
          'brazil': 'BRAZIL',
        },
        'ind': {
          'setting': 'Ganti Bahasa',
          // 'indo': 'Indonesia',
          'akomodasi': 'AKOMODASI',
          'rs': 'RUMAH SAKIT',
          'tukar': 'PENUKARAN UANG',
          'rental': 'RENTAL',
          'agen': 'AGEN WISATA',
          'resto': 'RESTORAN',
          'pasar': 'PASAR',
          'transport': 'TRANSPORTASI',
          'populer': 'Wisata Paling Populer',
          'gallery': 'GALERI',
          'detail': 'DETAIL',
          'lokasi': 'DETAILS',
          'info': 'INFORMASI',
          'tour': 'WISATA',
          'event': 'AGENDA',
          'berita': 'BERITA',
          'tipe': 'TIPE',
          'views': 'PENGUNJUNG',
          'pemilik': 'PEMILIK',
          'harga': 'HARGA',
          'sewa': 'HARGA SEWA',
          'telp': 'NO.HP',
          'cp': 'NO.HP',
          'kab': 'KABUPATEN',
          'kec': 'KECAMATAN',
          'tarif': 'TARIF WISATA',
          'indo': 'INDONESIA',
          'malay': 'MALAYSIA',
          'inggris': 'INGGRIS',
          'jepang': 'JEPANG',
          'china': 'CHINA',
          'india': 'INDIA',
          'rusia': 'RUSSIA',
          'korea': 'KOREA',
          'turki': 'TURKI',
          'spanyol': 'SPANYOL',
          'brazil': 'BRAZIL',
        },
        'my': {
          'setting': 'Tukar bahasa',
          // 'indo': 'Indonesia',
          'akomodasi': 'PENGINAPAN',
          'rs': 'HOSPITAL',
          'tukar': 'TUKAR DUIT',
          'rental': 'RENTAL',
          'agen': 'SEWAAN',
          'resto': 'RESTORAN',
          'pasar': 'PASARAN',
          'transport': 'PENGANGKUTAN',
          'populer': 'lawatan paling popular',
          'gallery': 'GALERI',
          'detail': 'BUTIRAN',
          'lokasi': 'DETAILS',
          'info': 'MAKLUMAT',
          'tour': 'LAWATAN',
          'event': 'AGENDA',
          'berita': 'BERITA',
          'tipe': 'TYPE',
          'views': 'VIEWS',
          'pemilik': 'PELAWAT',
          'harga': 'HARGA',
          'sewa': 'HARGA SEWA',
          'telp': 'NOMBOR TELEFON',
          'cp': 'NOMBOR TELEFON',
          'kab': 'REGENCY',
          'kec': 'MUKIM',
          'tarif': 'KADAR PELANCONGAN',
          'indo': 'INDONESIA',
          'malay': 'MALAYSIA',
          'inggris': 'BAHASA INGGERIS',
          'jepang': 'JEPUN',
          'china': 'CHINA',
          'india': 'INDIA',
          'rusia': 'RUSSIA',
          'korea': 'KOREA',
          'turki': 'Türkiye',
          'spanyol': 'SEPANYOL',
          'brazil': 'BRAZIL',
        },
        'jp': {
          'setting': '言語を変えてください',
          // 'indo': 'インドネシア',
          'akomodasi': '宿泊施設',
          'rs': '病院',
          'tukar': '両替',
          'rental': 'レンタル',
          'agen': 'ツアーエージェント',
          'resto': 'レストラン',
          'pasar': '市場',
          'transport': '交通機関',
          'populer': '最も人気のあるツアー',
          'gallery': 'ギャラリー',
          'detail': '詳細',
          'lokasi': '位置',
          'info': '情報',
          'tour': '旅行',
          'event': '議題',
          'berita': 'ニュース',
          'tipe': 'タイプ',
          'views': '訪問者',
          'pemilik': 'オーナー',
          'harga': '価格',
          'sewa': 'レンタル料金',
          'telp': '電話番号',
          'cp': '電話番号',
          'kab': '摂政',
          'kec': '準地区',
          'tarif': '観光料金',
          'indo': 'インドネシア',
          'malay': 'マレーシア',
          'inggris': '英語',
          'jepang': '日本',
          'china': '中国',
          'india': 'インド',
          'rusia': 'ロシア',
          'korea': '韓国',
          'turki': 'トゥルキエ',
          'spanyol': 'スペイン語',
          'brazil': 'ブラジル',
        },
        'cn': {
          'setting': '改变语言',
          // 'indo': '印度尼西亚',
          'akomodasi': '住宿',
          'rs': '医院',
          'tukar': '兑换外币',
          'rental': '租金',
          'agen': '旅行社',
          'resto': '餐厅',
          'pasar': '市场',
          'transport': '运输',
          'populer': '最受欢迎的旅游',
          'gallery': '画廊',
          'detail': '细节',
          'lokasi': '地点',
          'info': '信息',
          'tour': '旅游',
          'event': '议程',
          'berita': '消息',
          'tipe': '类型',
          'views': '参观者',
          'pemilik': '所有者',
          'harga': '价格',
          'sewa': '租金',
          'telp': '电话号码',
          'cp': '电话号码',
          'kab': '丽晶',
          'kec': '分地区',
          'tarif': '旅游价格',
          'indo': '印度尼西亚',
          'malay': '马来西亚',
          'inggris': '英语',
          'jepang': '日本',
          'china': '中国',
          'india': '印度',
          'rusia': '俄罗斯',
          'korea': '韩国',
          'turki': '土耳其语',
          'spanyol': '土耳其语',
          'brazil': '巴西',
        },
        'hindi': {
          'setting': 'भाषा बदलें',
          // 'indo': 'इंडोनेशिया',
          'akomodasi': 'आवास',
          'rs': 'अस्पताल',
          'tukar': 'विदेशी मुद्रा',
          'rental': 'किराया',
          'agen': 'टूर एजेंट',
          'resto': 'रेस्टोरेंट',
          'pasar': 'बाज़ार',
          'transport': 'यातायात',
          'populer': 'सबसे लोकप्रिय पर्यटन',
          'gallery': 'गेलरी',
          'detail': 'विवरण',
          'lokasi': 'जगह',
          'info': 'जानकारी',
          'tour': 'यात्रा',
          'event': 'कार्यसूची',
          'berita': 'समाचार',
          'tipe': 'प्रकार',
          'views': 'आगंतुकों',
          'pemilik': 'मालिक',
          'harga': 'कीमत',
          'sewa': 'किराये की कीमत',
          'telp': 'फ़ोन नंबर',
          'cp': 'फ़ोन नंबर',
          'kab': 'राज-प्रतिनिधि का पद',
          'kec': 'उप जिला',
          'tarif': 'पर्यटन दरें',
          'indo': 'इंडोनेशिया',
          'malay': 'मलेशिया',
          'inggris': 'अंग्रेज़ी',
          'jepang': 'जापान',
          'china': 'चीन',
          'india': 'भारत',
          'rusia': 'रूस',
          'korea': 'कोरिया',
          'turki': 'तुर्की',
          'spanyol': 'स्पैनिश',
          'brazil': 'ब्राज़ील',
        },
        'rs': {
          'setting': 'Изменить язык',
          // 'indo': 'Индонезия',
          'akomodasi': 'РАЗМЕЩЕНИЕ',
          'rs': 'БОЛЬНИЦА',
          'tukar': 'ОБМЕНЯТЬ ДЕНЬГИ',
          'rental': 'АРЕНДА',
          'agen': 'ТУРИСТИЧЕСКИЙ АГЕНТ',
          'resto': 'РЕСТОРАН',
          'pasar': 'РЫНОК',
          'transport': 'ТРАНСПОРТ',
          'populer': 'самые популярные туры',
          'gallery': 'ГАЛЕРЕЯ',
          'detail': 'ПОДРОБНОСТИ',
          'lokasi': 'РАСПОЛОЖЕНИЕ',
          'info': 'ИНФОРМАЦИЯ',
          'tour': 'ТУР',
          'event': 'ПОВЕСТКА ДНЯ',
          'berita': 'НОВОСТИ',
          'tipe': 'ТИП',
          'views': 'ПОСЕТИТЕЛИ',
          'pemilik': 'ВЛАДЕЛЕЦ',
          'harga': 'ЦЕНА',
          'sewa': 'ЦЕНА АРЕНДЫ',
          'telp': 'НОМЕР ТЕЛЕФОНА',
          'cp': 'НОМЕР ТЕЛЕФОНА',
          'kab': 'РЕГЕНЦИЯ',
          'kec': 'ПОДРАЙОН',
          'tarif': 'ТУРИСТИЧЕСКИЕ ТАРИФЫ',
          'indo': 'ИНДОНЕЗИЯ',
          'malay': 'МАЛАЙЗИЯ',
          'inggris': 'АНГЛИЙСКИЙ',
          'jepang': 'ЯПОНИЯ',
          'china': 'КИТАЙ',
          'india': 'ИНДИЯ',
          'rusia': 'РОССИЯ',
          'korea': 'КОРЕЯ',
          'turki': 'Турция',
          'spanyol': 'ИСПАНСКИЙ',
          'brazil': 'БРАЗИЛИЯ',
        },
        'kr': {
          'setting': '언어 변경',
          // 'indo': '인도네시아',
          'akomodasi': '숙소',
          'rs': '병원',
          'tukar': '환전',
          'rental': '렌탈',
          'agen': '여행사',
          'resto': '식당',
          'pasar': '시장',
          'transport': '운송',
          'populer': '가장 인기있는 투어',
          'gallery': '갤러리',
          'detail': '세부',
          'lokasi': '위치',
          'info': '정보',
          'tour': '관광',
          'event': '의제',
          'berita': '소식',
          'tipe': '유형',
          'views': '방문자',
          'pemilik': '소유자',
          'harga': '가격',
          'sewa': '임대 가격',
          'telp': '전화 번호',
          'cp': '전화 번호',
          'kab': '섭정 정치',
          'kec': '하위 지구',
          'tarif': '관광 요금',
          'indo': '인도네시아',
          'malay': '말레이시아',
          'inggris': '영어',
          'jepang': '일본',
          'china': '중국',
          'india': '인도',
          'rusia': '러시아',
          'korea': '한국',
          'turki': '투르키예',
          'spanyol': '스페인의',
          'brazil': '브라질',
        },
        'tr': {
          'setting': 'Dili değiştir',
          // 'indo': 'Endonezya',
          'akomodasi': 'KONAKLAMA',
          'rs': 'HASTANE',
          'tukar': 'PARA DEĞİŞİMİ',
          'rental': 'KİRALIK',
          'agen': 'TURİZM ACENTESİ',
          'resto': 'RESTORAN',
          'pasar': 'PAZAR',
          'transport': 'TOPLU TAŞIMA',
          'populer': 'en popüler turlar',
          'gallery': 'GALERİ',
          'detail': 'DETAYLAR',
          'lokasi': 'KONUM',
          'info': 'BİLGİ',
          'tour': 'TOR',
          'event': 'GÜNDEM',
          'berita': 'HABERLER',
          'tipe': 'TİP',
          'views': 'ZİYARETÇİ',
          'pemilik': 'MAL SAHİBİ',
          'harga': 'FİYAT',
          'sewa': 'KİRALIK FİYATI',
          'telp': 'TELEFON NUMARASI',
          'cp': 'TELEFON NUMARASI',
          'kab': 'naiplik',
          'kec': 'ALT BÖLGE',
          'tarif': 'TURİZM FİYATLARI',
          'indo': 'ENDONEZYA',
          'malay': 'MALEZYA',
          'inggris': 'İNGİLİZCE',
          'jepang': 'JAPONYA',
          'china': 'ÇİN',
          'india': 'HİNDİSTAN',
          'rusia': 'RUSSIA',
          'korea': 'KORE',
          'turki': 'türkiye',
          'spanyol': 'İSPANYOL',
          'brazil': 'BREZİLYA',
        },
        'sp': {
          'setting': 'Cambiar idioma',
          // 'indo': 'Indonesia',
          'akomodasi': 'ALOJAMIENTO',
          'rs': 'HOSPITAL',
          'tukar': 'CAMBIO DE MONEDA',
          'rental': 'ALQUILERES',
          'agen': 'AGENTE DE TURISMO',
          'resto': 'RESTAURANTE',
          'pasar': 'MERCADO',
          'transport': 'TRANSPORTE',
          'populer': 'excursiones más populares',
          'gallery': 'GALERÍA',
          'detail': 'DETALLES',
          'lokasi': 'UBICACIÓN',
          'info': 'INFORMACIÓN',
          'tour': 'RECORRIDO',
          'event': 'AGENDA',
          'berita': 'NOTICIAS',
          'tipe': 'TIPO',
          'views': 'VISITANTES',
          'pemilik': 'DUEÑO',
          'harga': 'PRECIO',
          'sewa': 'PRECIO DEL ALQUILER',
          'telp': 'NÚMERO DE TELÉFONO',
          'cp': 'NÚMERO DE TELÉFONO',
          'kab': 'REGENCIA',
          'kec': 'SUBDISTRITO',
          'tarif': 'TARIFAS TURÍSTICAS',
          'indo': 'INDONESIA',
          'malay': 'MALASIA',
          'inggris': 'INGLÉS',
          'jepang': 'JAPÓN',
          'china': 'PORCELANA',
          'india': 'INDIA',
          'rusia': 'RUSSIA',
          'korea': 'COREA',
          'turki': 'Turquía',
          'spanyol': 'ESPAÑOL',
          'brazil': 'BRASIL',
        },
        'br': {
          'setting': 'Mudar idioma',
          // 'indo': 'Indonésia',
          'akomodasi': 'ALOJAMENTO',
          'rs': 'HOSPITAL',
          'tukar': 'DINHEIRO DE TROCA',
          'rental': 'ALUGUEL',
          'agen': 'AGENTE DE TURISMO',
          'resto': 'RESTAURANTE',
          'pasar': 'MERCADO',
          'transport': 'TRANSPORTE',
          'populer': 'passeios mais populares',
          'gallery': 'GALERI',
          'detail': 'DETALHES',
          'lokasi': 'LOCALIZAÇÃO',
          'info': 'INFORMAÇÃO',
          'tour': 'PERCORRER',
          'event': 'AGENDA',
          'berita': 'NOTÍCIAS',
          'tipe': 'TIPO',
          'views': 'VISITANTES',
          'pemilik': 'PROPRIETÁRIO',
          'harga': 'PREÇO',
          'sewa': 'PRECO DE ALUGUEL',
          'telp': 'NÚMERO DE TELEFONE',
          'cp': 'NÚMERO DE TELEFONE',
          'kab': 'REGÊNCIA',
          'kec': 'SUB DISTRITO',
          'tarif': 'TAXAS DE TURISMO',
          'indo': 'INDONÉSIA',
          'malay': 'MALÁSIA',
          'inggris': 'INGLÊS',
          'jepang': 'JAPÃO',
          'china': 'CHINA',
          'india': 'ÍNDIA',
          'rusia': 'RÚSSIA',
          'korea': 'CORÉIA',
          'turki': 'Türkiye',
          'spanyol': 'ESPANHOL',
          'brazil': 'BRASIL',
        },
      };
}
